Fix/backoffice auto update materials categories
Taro-IT/frappe pull request #106
Opened 2021-12-01 23:00 UTC by JanLimpensG

2021-12-02 00:41 UTC, RGalaviz requested changes

2021-12-02 00:41 UTC, RGalaviz commented on apps/backoffice/frontend/components/Demo/category/AddCategory/index.tsx
> +      window.location.reload();
No sé si asi se supone que funcione, pero cuando pones una categoría con el mismo nombre te manda el label de color rojo, pero igual le hace reload a la página, pese a que no se editó la categoría, en materiales NO pasa esto.

2021-12-02 02:27 UTC, RGalaviz commented on apps/backoffice/frontend/components/Demo/category/AddCategory/index.tsx
> +      window.location.reload();
Si le das enter sigue pasando lo mismo, con el botón no pasa.

2021-12-02 22:10 UTC, JanLimpensG commented
En esta rama estoy haciendo los cambios al edit de producto, no cerrar el PR aún

2021-12-06 17:37 UTC, EricBL3 approved these changes

2021-12-06 17:40 UTC, merged

2021-12-06 17:41 UTC, dinnos commented
:tada: This PR is included in version 1.8.0-dev.6 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.8.0-dev.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-12-06 17:52 UTC, dinnos commented
:tada: This PR is included in version 1.9.0-dev.1 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.9.0-dev.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: