Fix/stripe in sale products
Taro-IT/frappe pull request #109
Opened 2021-12-03 23:16 UTC by EricBL3

2021-12-03 23:34 UTC, JanLimpensG requested changes

2021-12-03 23:34 UTC, JanLimpensG commented on apps/backoffice/frontend/components/Demo/order/OrderList/OrderCard/index.tsx
> +    const label = await axios.post(`${process.env.SKYDROPX_BASE_URL}/v1/labels`,
LGTM, sólo le falta pasar a variable de entorno la petición de la línea 85

2021-12-06 15:34 UTC, EricBL3 commented on .husky/pre-commit
> +#npx --no-install commitlint --edit "$1"
```suggestion
npx --no-install commitlint --edit "$1"
```

2021-12-06 17:33 UTC, jorgesanchez98 approved these changes
All OK computer

2021-12-06 17:34 UTC, merged

2021-12-06 17:52 UTC, dinnos commented
:tada: This PR is included in version 1.9.0-dev.1 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.9.0-dev.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: