Add collection use case (backend)
Taro-IT/frappe pull request #14
Opened 2021-09-29 03:49 UTC by Maualvm

2021-09-30 15:31 UTC, karlaromerox3 requested changes
El frontend que tienen no es igual al que habían diseñado, no se si ese fue el acuerdo? De ahí en fuera me parece bien. :)

2021-09-30 15:48 UTC, IvanDiazPeralta reviewed
Igual que la compañera Karla, lo veo bien. Pero revisen eso de la interfaz

2021-09-30 16:54 UTC, karlaromerox3 approved these changes
Lo vamos a aprobar para no tener dependencias con algunos archivos, pero pls chequen lo de la interfaz.

2021-09-30 16:54 UTC, merged

2021-09-30 16:57 UTC, dinnos commented
:tada: This PR is included in version 1.1.0-dev.2 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.1.0-dev.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-10-21 20:03 UTC, dinnos commented
:tada: This PR is included in version 1.2.0-dev.1 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0-dev.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-19 01:58 UTC, dinnos commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: