Feat/update category
Taro-IT/frappe pull request #20
Opened 2021-10-02 02:42 UTC by karlaromerox3

2021-10-05 13:40 UTC, karlaromerox3 commented on apps/api-gateway/src/container/commandHandlers.ts
> +      asClass(AccountSignUpCommandHandler),
Está dos veces el Account Sign up CH

2021-10-05 14:12 UTC, dinnos requested changes
eliminar el archivo yarn.lock y revisar issues de linting

2021-10-05 14:12 UTC, dinnos commented on apps/backoffice/frontend/components/Demo/category/CategoryList/index.tsx
> +    id: string,
agregar readonly

2021-10-05 14:12 UTC, dinnos commented on apps/backoffice/frontend/components/Demo/category/CategoryList/index.tsx
> +                    <Button title="Editar" className="ml-2 w-24" variant="cta" onClick={()=>{setEditModal(true);setCurrentCategory({id: category.id, name: category.name});setNameErrors(false)}}/>
pasar onClick a una función, cuando se hace esto en react puede generar problemas de performance (render)

2021-10-05 14:12 UTC, dinnos commented on apps/backoffice/frontend/components/Demo/category/CategoryList/index.tsx
> +                            <Button title="Guardar cambios" onClick={()=>{updateCategory(currentCategory.id, newName)}} variant="cta" className={"mt-4"} />
pasar onClick a función por posibles problemas de performance

2021-10-05 14:12 UTC, dinnos commented on libs/common/design-system/src/Modal/index.tsx
> +  toggleModal: (nv: boolean) => any;
cambiar any por unknown

2021-10-05 14:12 UTC, dinnos commented on libs/common/design-system/src/Modal/index.tsx
> +            onClick={() => toggleModal(false)}
cambiar onClick a una función

2021-10-05 18:46 UTC, Maualvm approved these changes
LGTM

2021-10-05 20:29 UTC, dinnos approved these changes

2021-10-05 20:36 UTC, merged

2021-10-05 20:39 UTC, dinnos commented
:tada: This PR is included in version 1.1.0-dev.7 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.1.0-dev.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-19 01:57 UTC, dinnos commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: