Feat/delete category
Taro-IT/frappe pull request #25
Opened 2021-10-07 18:11 UTC by karlaromerox3

2021-10-07 21:15 UTC, dinnos commented on apps/api-gateway/src/app.ts
> +  //app.use(helmet()); // Security Headers
si lo dejas comentado elimina el import

2021-10-07 21:16 UTC, dinnos commented on apps/backoffice/frontend/components/Demo/category/CategoryList/index.tsx
> +            requestDelete(id)
creo podrías simplificar esto al colocar el código de requestDelete en esta parte

2021-10-07 21:17 UTC, dinnos commented on apps/backoffice/frontend/components/Demo/category/CategoryList/index.tsx
>                      <EditButton id={category.id} name={category.name} />
se puede simplificar category. si haces destructuring en el map

2021-10-07 21:18 UTC, dinnos commented on libs/category/application/src/delete/CategoryDeleter.spec.ts
> +import {CategoryAlreadyExists, CategoryRepository, CategoryNotFound} from "@frappe/category/domain";
Elimina el import que se esta utilizando CategoryAlreadyExists

2021-10-07 21:18 UTC, dinnos commented on libs/category/application/src/delete/CategoryDeleter.ts
> +// Una Clase por lo general solo debe tener un método público
Elimina estos comentarios

2021-10-08 04:02 UTC, dinnos commented on libs/category/persistence/mongodb/src/utils/MongoCategoryRepository.ts
> +import { Console } from "console";
Elimina este import

2021-10-12 04:32 UTC, dinnos requested changes

2021-10-12 04:32 UTC, dinnos commented on libs/category/persistence/mongodb/src/utils/MongoCategoryRepository.ts
> +    const document = await collection.findOne({_id: id.value})
la lógica de findOne ya esta en el caso de uso cuando llamas al find tenerla aquí es redundante

2021-10-12 16:49 UTC, EricBL3 commented on apps/backoffice/frontend/components/Demo/category/CategoryList/index.tsx
> +    const ConfirmDeleteCategory = ({id}:buttonprops) => {
Si esto es un método o función no está siguiendo el estandar que es tener el nombre en camelCase. Si es otra cosa hay que definir un estándar para esto porque hay algunos que están en camelCase y otros en PascalCase

2021-10-13 20:41 UTC, merged

2021-10-13 20:42 UTC, dinnos commented
:tada: This PR is included in version 1.1.0-dev.25 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.1.0-dev.25)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-19 01:57 UTC, dinnos commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: