Feat/backend guide
Taro-IT/frappe pull request #46
Opened 2021-11-02 16:48 UTC by karlaromerox3

2021-11-02 23:54 UTC, EricBL3 submitted a review, later dismissed
el contenido lo vi bien, solo hay que aceptar los cambios de los typos

2021-11-02 23:54 UTC, EricBL3 commented on apps/docs/docs/guides/PPG02 - Guía para hacer un caso de uso en backend.md
> +4. Para llenar el archivo `CreateCategoryCommand.ts` deberás crear el payload necesario para crear una categoría en forma de una interfz. Además de un constructor para tu comando. Por ejemplo:
```suggestion
4. Para llenar el archivo `CreateCategoryCommand.ts` deberás crear el payload necesario para crear una categoría en forma de una interfaz. Además de un constructor para tu comando. Por ejemplo:
```

2021-11-02 23:54 UTC, EricBL3 commented on apps/docs/docs/guides/PPG02 - Guía para hacer un caso de uso en backend.md
> +  6. Crea un archivo `index.ts` al nivel de la carpeta **model**, el cual debe exportar cada srchivo que hayas creado. Por ejemplo:
```suggestion
  6. Crea un archivo `index.ts` al nivel de la carpeta **model**, el cual debe exportar cada archivo que hayas creado. Por ejemplo:
```

2021-11-04 02:11 UTC, RGalaviz approved these changes
Buena guía, tal vez agregar algo de los Errors, pero sería una guía diferente, el nivel de detalle es perfecto, gracias de verdad.

2021-11-04 02:17 UTC, dinnos requested changes

2021-11-04 02:17 UTC, dinnos commented on apps/docs/docs/guides/PPG02 - Guía para hacer un caso de uso en backend.md
> +1.  Para crear una librería de dominio debes correr el comando
estaría bien colocar lo de las tres carpetas de Domain (model, error, utils, events)

2021-11-04 02:17 UTC, dinnos commented on apps/docs/docs/guides/PPG02 - Guía para hacer un caso de uso en backend.md
> +  - CasoDeUsoRepository.ts
En sí no es un caso de uso, es la definición del "Contrato" para acceso de datos o integración para un servicio externo I/O

2021-11-04 02:17 UTC, dinnos commented on apps/docs/docs/guides/PPG02 - Guía para hacer un caso de uso en backend.md
> +3. Después crea una carpeta que se llame `utils` y crea un archivo que se llame `Mongo<NombreLib>Repository.ts`, además de un archivo llamado `index.ts`. La estructura debe quedar como se muestra en
Colocar que en este caso debe de implementar lo definido en los contratos de Domain (utils)

2021-11-04 02:17 UTC, dinnos commented on apps/docs/docs/guides/PPG02 - Guía para hacer un caso de uso en backend.md
> +1.  Para crear una librería de aplicación debes correr el comando
Colocar la definición de Casos -> Read (Queries) y Write (Commands)

2021-11-04 05:11 UTC, karlaromerox3 commented on apps/docs/docs/guides/PPG02 - Guía para hacer un caso de uso en backend.md
> +1.  Para crear una librería de dominio debes correr el comando
AAAAAA error los agrego, events si no c nada :C

2021-11-05 03:36 UTC, karlaromerox3 commented
Añadí los cambios que me pidió Vlad

2021-11-08 18:44 UTC, RGalaviz approved these changes

2021-11-09 19:41 UTC, Maualvm approved these changes
LGTM

2021-11-09 19:43 UTC, dinnos approved these changes

2021-11-09 22:07 UTC, merged

2021-11-09 22:09 UTC, dinnos commented
:tada: This PR is included in version 1.2.0-dev.15 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0-dev.15)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-19 01:56 UTC, dinnos commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: