feat: create api-gateway guide
Taro-IT/frappe pull request #48
Opened 2021-11-04 15:16 UTC by karlaromerox3

2021-11-04 18:29 UTC, Maualvm requested changes
Hecho por Vlad y Mau

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +  1. Dentro de la carpeta `apps/api-gateway/src` crea una carpeta para tu caso de uso con un nombre significativo
En lugar de nombre significativo, debería ser el nombre del modulo (product, category, etc) todo en minúsculas.

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +  3. Crea un archivo para tu handler con el nombre `<accion><Caso>Handler.ts`, por ejemplo `createCategoryHandler.ts`, el cuál tendrá algo similar al código siguiente:
Insertar un enter después de esta línea para que agarre bien la sintáxis del bloque de código

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +3. Dentro de tu dto deberás incluir todos los campos que recibes en los request de la API y validarlos con decoradores (class-validators). Puedes ver la lista de decoradores disponibles [aquí](https:
Especificar que todos los campos deben de ser `readonly`

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +1. En el nivel root de caso de uso, crea un archivo que se llame `<caso>.routing.ts`, en el cual vas a registrar todas las rutas con sus métodos HTTP, además de los dtos que validarán dichas rutas. E
cambiar `<caso>` por `<modulo>`

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +  // router.<HTTP-Request>('/ruta', makeValidateBody(dtos.<Nombre-dto>), handlers.<nombre-handler>(<bus>));
Especificar que `makeValidateBody` es opcional, ya que no siempre se necesitan usar los dtos

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +  router.post('/', makeValidateBody(dtos.CreateCategoryDto), handlers.createCategoryHandler(commandBus));
Especificar que makeValidateBody es opcional, ya que no siempre se necesitan usar los dtos

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +  router.patch('/:id', makeValidateBody(dtos.UpdateCategoryDto), handlers.updateCategoryHandler(commandBus));
Especificar que makeValidateBody es opcional, ya que no siempre se necesitan usar los dtos

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +      readonly categoryRouting: express.Router;
Especificar que este nombre debe ser igual al de la línea 137

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +1. Al nivel de `src` encuentra la carpeta `container` y abre el archivo `commandHandlers.ts`, en el cuál registrarás los handlers que hayas creado en las librerías.
Especificar que `handlers` deben ser los de las librerías (en commands van los comandos, y en queries, van los queries)

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +- Un endpoint de API listo para probarse con Postman o Imsomnia
Uno o más endpoints

2021-11-04 18:29 UTC, Maualvm commented on apps/docs/docs/guides/PPG04-guia-gateway.md
> +
Agregar al buen y exitoso (en todo) Mau a la Auditoria

2021-11-09 19:40 UTC, Maualvm approved these changes
LGTM

2021-11-09 19:44 UTC, dinnos approved these changes

2021-11-09 22:07 UTC, merged

2021-11-09 22:09 UTC, dinnos commented
:tada: This PR is included in version 1.2.0-dev.15 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0-dev.15)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-19 01:56 UTC, dinnos commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: