Feat/add material
Taro-IT/frappe pull request #53
Opened 2021-11-14 03:58 UTC by karlaromerox3

2021-11-14 04:18 UTC, karlaromerox3 commented
Aqui termina el caso de uso create

2021-11-14 18:22 UTC, karlaromerox3 commented
Aquí termina Read y Update

2021-11-14 19:33 UTC, karlaromerox3 commented
Aquí termina el caso de uso delete

2021-11-15 17:39 UTC, EricBL3 submitted a review, later dismissed
Para el caso frappe-71 (create) todo se ve bien.

2021-11-15 17:39 UTC, EricBL3 commented on libs/material/domain/src/model/Material.ts
> +  constructor(readonly id: MaterialId, readonly name: MaterialName, readonly image: MaterialImage, readonly isActive: MaterialIsActive, readonly deletedAt?: MaterialDeletedAt) {}
Esto se podría cambiar para mejorar la legibilidad del código
```suggestion
  constructor(
    readonly id: MaterialId, 
    readonly name: MaterialName, 
    readonly image: MaterialImage, 
    readonly isActive: MaterialIsActive, 
    readonly deletedAt?: MaterialDeletedAt
  ) {}
```

2021-11-15 17:39 UTC, EricBL3 commented on libs/material/domain/src/model/Material.ts
> +    return new Material(new MaterialId(primitives.id), new MaterialName(primitives.name), new MaterialImage(primitives.image), new MaterialIsActive(primitives.isActive), new MaterialDeletedAt(primiti
Esto se podría cambiar para mejorar la legibilidad del código
```suggestion
    return new Material(
      new MaterialId(primitives.id), 
      new MaterialName(primitives.name), 
      new MaterialImage(primitives.image), 
      new MaterialIsActive(primitives.isActive), 
      new MaterialDeletedAt(primitives.deletedAt)
    );
```

2021-11-15 17:39 UTC, EricBL3 commented on libs/material/test/src/utils/MaterialMother.ts
> +    return new Material(new MaterialId(UuidMother.random()), new MaterialName(StringMother.random()), new MaterialImage(StringMother.random()), new MaterialIsActive(true));
Esto se podría cambiar para mejorar la legibilidad del código
```suggestion
    return new Material(
      new MaterialId(UuidMother.random()), 
      new MaterialName(StringMother.random()), 
      new MaterialImage(StringMother.random()), 
      new MaterialIsActive(true)
    );
```

2021-11-15 17:39 UTC, EricBL3 commented on libs/material/test/src/utils/MaterialMother.ts
> +    return new Material(new MaterialId(UuidMother.random()), new MaterialName(StringMother.random()), new MaterialImage(StringMother.random()), new MaterialIsActive(false), new MaterialDeletedAt(new
Esto se podría cambiar para mejorar la legibilidad del código
```suggestion
    return new Material(
      new MaterialId(UuidMother.random()), 
      new MaterialName(StringMother.random()), 
      new MaterialImage(StringMother.random()), 
      new MaterialIsActive(false), 
      new MaterialDeletedAt(new Date())
    );
```

2021-11-16 02:07 UTC, IvanDiazPeralta commented on libs/material/ui/src/components/MaterialList/index.tsx
> +            return <MaterialCard id={material.id} key={material.id} name={material.name} image={material.image} setDeleteModal={setDeleteModal} setNameErrors={setNameErrors} setEditModal={setEditModa
Aquí creo que conviene hacer lo que ya comentó Eric en los otros archivos, acomodarlo para que sea más fácil leerlo

2021-11-16 02:08 UTC, IvanDiazPeralta approved these changes
Lo de Delete se ve bien, solo los comentarios de estética del código

2021-11-16 16:08 UTC, JanLimpensG approved these changes

2021-11-17 04:22 UTC, Maualvm requested changes
Lo de upadte lo veo bien, solo que pase los tests y creo que se podria mergear

2021-11-19 17:58 UTC, EricBL3 approved these changes

2021-11-19 20:07 UTC, Maualvm approved these changes

2021-11-19 20:48 UTC, merged

2021-11-19 20:50 UTC, dinnos commented
:tada: This PR is included in version 1.2.0-dev.31 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0-dev.31)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-21 03:41 UTC, dinnos commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: