Architecture handbook for frappe71
Taro-IT/frappe pull request #57
Opened 2021-11-15 00:37 UTC by karlaromerox3

2021-11-15 17:20 UTC, EricBL3 requested changes

2021-11-15 17:20 UTC, EricBL3 commented on apps/docs/docs/architecture/material/create.md
> +
Creo que en esta parte de diagramas conviene más poner ss porque solo nosotros tenemos acceso al Confluence y pide tener cuenta para ver lo de lucidchart.

2021-11-16 23:54 UTC, EricBL3 reviewed
El de create lo veo bien, creo todavía falta que se verifique lo del update para hacer el merge

2021-11-17 02:41 UTC, karlaromerox3 commented
@EricBL3 pls apruébalo porque no me va a dejar hacer el merge

2021-11-17 23:34 UTC, EricBL3 approved these changes

2021-11-17 23:34 UTC, merged

2021-11-17 23:36 UTC, dinnos commented
:tada: This PR is included in version 1.2.0-dev.25 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0-dev.25)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-19 01:55 UTC, dinnos commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: