Feat/password reset
Taro-IT/frappe pull request #59
Opened 2021-11-15 06:28 UTC by dinnos

2021-11-15 16:50 UTC, EricBL3 commented
No revisar hasta que esté el caso completo

2021-11-17 00:17 UTC, EricBL3 requested changes
Falta poner un comentario en la primera línea de cada archivo el identificador de la user story.

2021-11-17 00:17 UTC, EricBL3 commented on libs/account/domain/src/error/UserNotFound.ts
> +    super(id ? `user with id: ${ id } does not exist` : 'user does not exist');
El error debería ir en español porque en teoría es el que se le mostraría a los usuarios

2021-11-17 00:17 UTC, EricBL3 commented on libs/common/persistence/mongodb/src/utils/MongoCriteriaMapper.ts
No hubo cambios en este archivo pero de una vez estaría bien comentarla porque si es de la capa de persistence.

2021-11-24 01:42 UTC, IvanDiazPeralta commented on libs/common/persistence/mongodb/src/utils/MongoCriteriaMapper.ts
Todavía falta comentar este archivo

2021-11-24 01:50 UTC, IvanDiazPeralta commented on apps/api-gateway/src/account/dto/UpdatePassword.dto.ts
> +import { IsEmail, IsNotEmpty, MinLength } from 'class-validator';
Falta comentar la US

2021-11-24 01:50 UTC, IvanDiazPeralta commented on apps/api-gateway/src/account/handlers/updateUserPasswordHandler.ts
> +import { CommandBus } from '@tshio/command-bus';
Falta comentar la US

2021-11-24 01:51 UTC, IvanDiazPeralta commented on apps/api-gateway/src/user/dto/CreatePasswordResetCode.dto.ts
> +//User story: frappe-503
Falta comentar la US

2021-11-24 01:51 UTC, eacp commented on apps/api-gateway/src/account/dto/UpdatePassword.dto.ts
> +import { IsEmail, IsNotEmpty, MinLength } from 'class-validator';
Como dice @IvanDiazPeralta , tiene que ser en todas las US, se tiene que comentar que caso resuelve. Si un archivo resuelve mas de una, se pone. Creo que hay una excepcion para el mongo persistance

2021-11-24 01:51 UTC, IvanDiazPeralta commented on apps/api-gateway/src/user/handlers/createPasswordResetCodeHandler.ts
> +import { CommandBus } from '@tshio/command-bus';
Falta comentar la US

2021-11-24 01:51 UTC, IvanDiazPeralta commented on libs/account/application/src/create/password/CreatePasswordResetCodeCommand.ts
> +import { Command } from '@tshio/command-bus';
Falta comentar la US

2021-11-24 01:52 UTC, IvanDiazPeralta commented on libs/account/application/src/create/password/CreatePasswordResetCodeCommandHandler.ts
> +import { CommandHandler } from '@tshio/command-bus';
Falta comentar la US

2021-11-24 01:52 UTC, IvanDiazPeralta commented on libs/account/application/src/create/password/PasswordResetCodeCreator.ts
> +import { EventDispatcher } from '@tshio/event-dispatcher';
Falta comentar la US

2021-11-24 01:53 UTC, IvanDiazPeralta commented on libs/account/domain/src/event/PasswordResetCodeCreated.ts
> +import { Event } from '@tshio/event-dispatcher';
Falta comentar la US

2021-11-24 01:54 UTC, IvanDiazPeralta commented on libs/account/application/src/user/password/UserPasswordUpdater.ts
> +import { UserSearcher } from '../search';
Falta comentar US

2021-11-24 01:54 UTC, IvanDiazPeralta commented on libs/account/application/src/user/password/UpdateUserPasswordCommandHandler.ts
> +import { CommandHandler } from '@tshio/command-bus';
Falta comentar US

2021-11-24 01:54 UTC, IvanDiazPeralta commented on libs/account/application/src/user/password/UpdateUserPasswordCommand.ts
> +import { Command } from '@tshio/command-bus';
Falta comentar la US

2021-11-24 02:45 UTC, IvanDiazPeralta approved these changes
LGTM

2021-11-24 03:33 UTC, EricBL3 approved these changes

2021-11-24 03:33 UTC, merged

2021-11-24 03:37 UTC, dinnos commented
:tada: This PR is included in version 1.2.0-dev.39 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.2.0-dev.39)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-26 21:28 UTC, dinnos commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on [GitHub release](https://github.com/Taro-IT/frappe/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: